(function(){var f=true,g=null,i=false,aa=encodeURIComponent,j=navigator,ba=undefined,k=parseInt,m=document,ca=decodeURIComponent,o=Math;function da(a,b){return a.width=b}function ea(a,b){return a.toString=b}function fa(a,b){return a.height=b}
var p="appendChild",q="push",r="valueOf",s="width",ga="round",ha="slice",t="replace",ia="floor",ja="cookie",ka="charAt",la="_height_",v="indexOf",ma="domain",w="write",na="match",oa="opera",x="_html_",pa="createElement",y="getParameter",qa="addEventListener",ra="referrer",sa="attachEvent",ta="name",ua="contentWindow",va="getTime",wa="getElementsByTagName",z="toString",A="length",xa="plugins",B="prototype",C="document",D="split",E="userAgent",F="screen",G="style",ya="body",za="_width_",Aa="call",Ba=
"random",Ca="_is_afc_",I="substring",Da="navigator",Ea="height",J="join",Ga="toLowerCase",K=this,Ha=function(a,b,c){a=a[D](".");c=c||K;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[A]&&(d=a.shift());)if(!a[A]&&b!==ba)c[d]=b;else c=c[d]?c[d]:(c[d]={})};o[ia](o[Ba]()*2147483648)[z](36);
var Ia=function(a,b){var c=b||K;if(arguments[A]>2){var d=Array[B][ha][Aa](arguments,2);return function(){var e=Array[B][ha][Aa](arguments);Array[B].unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},L=function(a,b,c){Ha(a,b,c)},Ja=function(a,b,c){a[b]=c},Ka=function(a,b){function c(){}c.prototype=b[B];a.ua=b[B];a.prototype=new c};var La=function(a,b){a=parseFloat(a);return isNaN(a)||a>1||a<0?b:a},Ma=function(a,b){if(a=="true")return f;if(a=="false")return i;return b},Na=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,Oa=function(a,b){if(!a)return b;return(a=a[na](Na))?a[0]:b};var Pa=function(){return Oa("","pagead2.googlesyndication.com")};var M=window;var Qa=function(a,b){da(this,a);fa(this,b)};Qa[B].floor=function(){da(this,o[ia](this[s]));fa(this,o[ia](this[Ea]));return this};Qa[B].round=function(){da(this,o[ga](this[s]));fa(this,o[ga](this[Ea]));return this};var Ta=function(a){if(a[v]("&")!=-1)return"document"in K&&a[v]("<")==-1?Ra(a):Sa(a);return a},Ra=function(a){var b=K[C][pa]("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},Sa=function(a){return a[t](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c[ka](0)=="#"){c=Number("0"+c.substr(1));if(!isNaN(c))return String.fromCharCode(c)}return b}})},Va=function(a,b){var c=0;a=
String(a)[t](/^[\s\xa0]+|[\s\xa0]+$/g,"")[D](".");b=String(b)[t](/^[\s\xa0]+|[\s\xa0]+$/g,"")[D](".");for(var d=o.max(a[A],b[A]),e=0;c==0&&e<d;e++){var l=a[e]||"",h=b[e]||"",n=new RegExp("(\\d*)(\\D*)","g"),u=new RegExp("(\\d*)(\\D*)","g");do{var P=n.exec(l)||["","",""],H=u.exec(h)||["","",""];if(P[0][A]==0&&H[0][A]==0)break;c=P[1][A]==0?0:k(P[1],10);var Fa=H[1][A]==0?0:k(H[1],10);c=Ua(c,Fa)||Ua(P[2][A]==0,H[2][A]==0)||Ua(P[2],H[2])}while(c==0)}return c},Ua=function(a,b){if(a<b)return-1;else if(a>
b)return 1;return 0};var Wa,Xa,Ya,Za,$a,ab,bb,cb,db,eb=function(){return K[Da]?K[Da][E]:g},fb=function(){return K[Da]},gb=function(){$a=Za=Ya=Xa=Wa=i;var a;if(a=eb()){var b=fb();Wa=a[v]("Opera")==0;Xa=!Wa&&a[v]("MSIE")!=-1;Za=(Ya=!Wa&&a[v]("WebKit")!=-1)&&a[v]("Mobile")!=-1;$a=!Wa&&!Ya&&b.product=="Gecko"}};gb();
var hb=Wa,ib=Xa,jb=$a,kb=Ya,lb=Za,mb=function(){var a=fb();return a&&a.platform||""},nb=mb(),ob=function(){ab=nb[v]("Mac")!=-1;bb=nb[v]("Win")!=-1;cb=nb[v]("Linux")!=-1;db=!!fb()&&(fb().appVersion||"")[v]("X11")!=-1};ob();var pb=function(){var a="",b;if(hb&&K[oa]){a=K[oa].version;a=typeof a=="function"?a():a}else{if(jb)b=/rv\:([^\);]+)(\)|;)/;else if(ib)b=/MSIE\s+([^\);]+)(\)|;)/;else if(kb)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(eb()))?a[1]:""}return a},qb=pb(),rb={};var sb=function(a){var b=a[C];if(kb&&!(rb["500"]||(rb["500"]=Va(qb,"500")>=0))&&!lb){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a[C].documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new Qa(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!hb||hb&&(rb["9.50"]||(rb["9.50"]=Va(qb,"9.50")>=0)))?b.documentElement:b[ya];return new Qa(a.clientWidth,a.clientHeight)};var tb="http://"+Pa()+"/pagead/show_ads.js";function N(a){return typeof aa=="function"?aa(a):escape(a)}function ub(a,b,c){var d=m[pa]("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=m[wa]("head")[0];if(!e)return i;window.setTimeout(function(){e[p](d)},0);return f}function vb(a,b){if(a[sa]){a[sa]("onload",b);return f}if(a[qa]){a[qa]("load",b,i);return f}return i}function wb(a){if(a in xb)return xb[a];return xb[a]=j[E][Ga]()[v](a)!=-1}var xb={};
function yb(){return wb("msie")&&!window[oa]}
function zb(){if(j[xa]&&j.mimeTypes[A]){var a=j[xa]["Shockwave Flash"];if(a&&a.description)return a.description[t](/([a-zA-Z]|\s)+/,"")[t](/(\s)+r/,".")}else if(j[E]&&j[E][v]("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a[z]()}else if(yb()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==
6)return a[z]()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(l){}}if(b){a=b.GetVariable("$version")[D](" ")[1];return a[t](/,/g,".")}}return"0"}function Ab(a,b){if(!(o[Ba]()<1.0E-4)){var c=o[Ba]();if(c<b){b=o[ia](c/b*a[A]);return a[b]}}return""}
var Bb=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history[A];a.u_java=j.javaEnabled();if(window[F]){a.u_h=window[F][Ea];a.u_w=window[F][s];a.u_ah=window[F].availHeight;a.u_aw=window[F].availWidth;a.u_cd=window[F].colorDepth}if(j[xa])a.u_nplug=j[xa][A];if(j.mimeTypes)a.u_nmime=j.mimeTypes[A]},Db=function(a){var b=M;if(a&&b.top!=b)b=b.top;try{return b[C]&&!b[C][ya]?new Qa(-1,-1):sb(b||window)}catch(c){return new Qa(-12245933,-12245933)}},Eb=function(a,b){var c=a[A];if(c==0)return 0;
b=b||305419896;for(var d=0;d<c;d++){var e=a.charCodeAt(d);b^=(b<<5)+(b>>2)+e&4294967295}return b},Fb=function(a){if(a==a.top)return 0;var b=[];b[q](m.URL);a[ta]&&b[q](a[ta]);a=f;a=Db(!a);b[q](a[s][z]());b[q](a[Ea][z]());b=Eb(b[J](""));return b>0?b:4294967296+b};var O=function(a){this.ja=a;this.W=[];this.V=0;this.H=[];this.da=0;this.N=[];this.ca=i;this.g=this.$="";this.ba=i},Gb=function(a,b,c){var d=a.ja[c],e=a.W;a.ja[c]=function(l){if(l&&l[A]>0){var h=l[A]>1?l[1].url:g;e[q]([b,Ta(l[0].url),h])}d(l)}},Hb=function(a){a.V++},Ib=function(a,b){a.H[q](b)},Jb="http://"+Pa()+"/pagead/osd.js",Lb=function(a){if(!a.ca){vb(M,Kb);ub(Jb);a.ca=f}},Mb=function(a,b){if(a.V>0){var c=m[wa]("iframe");a=a.ba?"google_ads_iframe_":"google_ads_frame";for(var d=0;d<c[A];d++){var e=
c.item(d);e.src&&e[ta]&&e[ta][v](a)==0&&b(e,e.src)}}},Nb=function(a,b){a=a.W;if(a[A]>0)for(var c=m[wa]("a"),d=0;d<c[A];d++)for(var e=0;e<a[A];e++)if(c.item(d).href==a[e][1]){var l=c.item(d).parentNode;if(a[e][2])for(var h=l,n=0;n<4;n++){if(h.innerHTML[v](a[e][2])>0){l=h;break}h=h.parentNode}b(l,a[e][0]);a.splice(e,1);break}},Pb=function(a,b){for(var c=0;c<a.H[A];c++){var d=a.H[c],e=Ob(d);if(e)(e=m.getElementById("google_ads_div_"+e))&&b(e,d)}};O[B].T=function(a){Nb(this,a);Pb(this,a);Mb(this,a)};
O[B].setupOsd=function(a,b,c){this.da=a;this.$=b;this.g=c};O[B].getOsdMode=function(){return this.da};O[B].getEid=function(){return this.$};O[B].getCorrelator=function(){return this.g};O[B].U=function(){return this.W[A]+this.V+this.H[A]};O[B].setValidOutputTypes=function(a){this.N=a};
O[B].registerAdBlockByType=function(a,b,c){if(this.N[A]>0){for(var d=0;d<this.N[A];d++)if(this.N[d]==a){this.ba=c;if(a=="js")Gb(this,b,"google_ad_request_done");else if(a=="html")Hb(this);else a=="json_html"&&Ib(this,b)}Lb(this)}};var Ob=function(a){if((a=a[na](/[&\?](?:slotname)=([^&]+)/))&&a[A]==2)return a[1];return""},Kb=function(){M.google_osd_page_loaded=f},Qb=function(){window.__google_ad_urls||(window.__google_ad_urls=new O(window));return window.__google_ad_urls};
L("Goog_AdSense_getAdAdapterInstance",Qb);L("Goog_AdSense_OsdAdapter",O);L("Goog_AdSense_OsdAdapter.prototype.numBlocks",O[B].U);L("Goog_AdSense_OsdAdapter.prototype.findBlocks",O[B].T);L("Goog_AdSense_OsdAdapter.prototype.getOsdMode",O[B].getOsdMode);L("Goog_AdSense_OsdAdapter.prototype.getEid",O[B].getEid);L("Goog_AdSense_OsdAdapter.prototype.getCorrelator",O[B].getCorrelator);L("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",O[B].setValidOutputTypes);
L("Goog_AdSense_OsdAdapter.prototype.setupOsd",O[B].setupOsd);L("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",O[B].registerAdBlockByType);var Rb=La("0.005",0),Sb=La("0.01",0),Tb=La("0.01",0),Vb=La("0.001",0),Wb=La("0.006",0),Xb=La("0.008",0);var Yb=Ma("false",i);var Zb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},$b={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},ac={google_only_pyv_ads:"pyv",
google_with_pyv_ads:"withpyv"};var cc=function(a){this.a=this.S=a;bc(this)},dc,ec=function(){if(dc)return dc;var a=window.google_persistent_state;if(typeof a!="object"||typeof a.S!="object"){a=window;return window.google_persistent_state=dc=new cc(a)}return dc=window.google_persistent_state},bc=function(a){Q(a,1,i);Q(a,2,i);Q(a,3,g);Q(a,4,0);Q(a,5,0);Q(a,6,0);Q(a,7,(new Date)[va]());Q(a,8,{});Q(a,9,{});Q(a,10,{});Q(a,11,[]);Q(a,13,0);Q(a,12,0)},fc=function(a){switch(a){case 1:return"google_new_domain_enabled";case 2:return"google_new_domain_checked";
case 3:return"google_exp_persistent";case 4:return"google_num_sdo_slots";case 5:return"google_num_0ad_slots";case 6:return"google_num_ad_slots";case 7:return"google_correlator";case 8:return"google_prev_ad_formats_by_region";case 9:return"google_prev_ad_slotnames_by_region";case 10:return"google_num_slots_by_channel";case 11:return"google_viewed_host_channels";case 12:return"google_num_slot_to_show";case 13:return"google_unique_id"}},gc=function(a,b){b=fc(b);return a=a.S[b]},hc=function(a,b,c){return a.S[fc(b)]=
c},Q=function(a,b,c){a=a.S;b=fc(b);if(a[b]===ba)return a[b]=c;return a[b]};var ic=m,R=j,S=window;
function jc(){var a=ic[ja],b=o[ga]((new Date)[va]()/1E3),c=S.google_analytics_domain_name;c=typeof c=="undefined"?kc("auto"):kc(c);var d=a[v]("__utma="+c+".")>-1,e=a[v]("__utmb="+c)>-1,l=a[v]("__utmc="+c)>-1,h={},n=!!S&&!!S.gaGlobal;if(d){a=a[D]("__utma="+c+".")[1][D](";")[0][D](".");h.sid=e&&l?a[3]+"":n&&S.gaGlobal.sid?S.gaGlobal.sid:b+"";h.vid=a[0]+"."+a[1];h.from_cookie=f}else{h.sid=n&&S.gaGlobal.sid?S.gaGlobal.sid:b+"";h.vid=n&&S.gaGlobal.vid?S.gaGlobal.vid:(o[ga](o[Ba]()*2147483647)^lc()&2147483647)+
"."+b;h.from_cookie=i}h.dh=c;h.hid=n&&S.gaGlobal.hid?S.gaGlobal.hid:o[ga](o[Ba]()*2147483647);return S.gaGlobal=h}function lc(){var a=ic[ja]?ic[ja]:"",b=S.history[A],c,d=[R.appName,R.version,R.language?R.language:R.browserLanguage,R.platform,R[E],R.javaEnabled()?1:0][J]("");if(S[F])d+=S[F][s]+"x"+S[F][Ea]+S[F].colorDepth;else if(S.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c[F][s]+"x"+c[F][Ea]}d+=a;d+=ic[ra]?ic[ra]:"";for(a=d[A];b>0;)d+=b--^a++;return mc(d)}
function mc(a){var b=1,c=0,d;if(!(a==ba||a=="")){b=0;for(d=a[A]-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function kc(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=ic[ma];if("www."==a[I](0,4))a=a[I](4,a[A])}return mc(a[Ga]())};function nc(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=m[ma]}ea(nc[B],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function oc(){this.w=pc(this);this.P=i;if(!this.w)this.P=qc(this)}oc[B].O="__gads=";oc[B].C="GoogleAdServingTest=";oc[B].L=function(a){this.r=a._cookies_[0];if(this.r!=g){this.w=this.r._value_;rc(this)}};Ja(oc[B],"setCookieInfo",oc[B].L);
var sc=function(a,b){a=(new Date)[r]();var c=new Date;c.setTime(a+b);return c},tc=function(a){var b=15552E6;a=sc(a,b);b="ID=12345:T="+b;var c="/",d=m[ma];return new nc(b,a[r](),c,d)},uc="http://"+Oa("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",vc=function(a,b){if(!(a.w||!a.P)){a="script";var c=m[ma];b=uc+"&client="+N(b)+"&domain="+N(c);m[w]("<"+a+' src="'+b+'"></'+a+">")}},qc=function(a){m.cookie=a.C+"Good";var b=wc(a,
a.C);if(b=b=="Good"){var c=sc(a,-1);m.cookie=a.C+"; expires="+c.toGMTString()}return b},pc=function(a){return a=wc(a,a.O)},wc=function(a,b){a=m[ja];var c=a[v](b),d="";if(c!=-1){b=c+b[A];c=a[v](";",b);if(c==-1)c=a[A];d=a[I](b,c)}return d},rc=function(a){if(a.r!=g)if(a.w){var b=new Date;b.setTime(1E3*a.r._expires_);var c=a.r._domain_;a=a.O+a.w+"; expires="+b.toGMTString()+"; path="+a.r._path_+"; domain=."+c;m.cookie=a}};function xc(a,b){try{return a.top[C].URL==b.URL}catch(c){}return i};var yc=new RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),zc=function(a){return a&&ca(a)};var Ac=function(a){this.ia=(this.Q=a&&a.GA_jstiming)&&this.Q.load};Ac[B].tick=function(a,b){this.ia.tick(a,b)};Ac[B].report=function(a){var b={};b.e=a;this.Q.report(this.ia,b)};var Bc=function(){};Ka(Bc,Ac);Bc[B].tick=function(){};Bc[B].report=function(){};var Cc=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var T=M&&o[Ba]()<Rb&&M.GA_jstiming&&M.GA_jstiming.load&&M.location.protocol=="http:"?new Ac(M):new Bc(M);T.tick("js_load");function U(a){return typeof a=="function"}function Dc(a,b){if(typeof a!="string"||a[A]==0)return g;else if(typeof b!="string"||b[A]==0)return g;return Ec(V(),a,b)}L("GA_googleAddSlot",Dc);function _GA_googleInitializeAdEngine(a){if(!W()){Fc(Gc(a));Hc(W())}}L("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function Ic(){V().ka=f;_GA_googleInitializeAdEngine(g);var a=W().h;a=="sync"||a=="sync_sra"?W().k():Jc(V())}L("GA_googleFetchAds",Ic);function Kc(){_GA_googleInitializeAdEngine("iframe");vc(window._GA_googleCookieHelper,window.GS_googleGetIdsForAdSenseService())}L("GA_googleUseIframeRendering",Kc);function Lc(){var a=window.GA_googleEnv[y]("google_ad_impl");a==g&&window.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}L("GA_googleUseSyncSRARendering",Lc);
function Mc(a){window.GA_googleEnv.setParameter("google_domain_reset_url",a)}L("GA_googleDomainResetUrl",Mc);function Nc(a){if(W()!=g)if(W().h!="iframe"){if(Oc(W()))if(W().M){var b=Pc(V(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(Qc(W(),a)!=g&&!W().m)return;W().o(a)}}L("GA_googleFillSlot",Nc);function Rc(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(W()!=g)if(W().h=="iframe"){Ec(V(),a,b);a=new Sc(c,d,i,f);Tc(V(),b,a);W().o(b)}}L("GA_googleFillSlotWithSize",Rc);
function Uc(){Vc(new Wc(Zb));Fc(g)}L("GA_googleResetAll",Uc);window.google_noFetch=i;function Xc(){window.google_noFetch=f}L("GA_googleNoFetch",Xc);function Yc(){window.google_delayFetch=f}L("GA_googleDelayFetch",Yc);function Sc(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ea(Sc[B],function(){return"[GA_GoogleAdSlotAttr: width="+this[za]+", height="+this[la]+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function Zc(a){var b={};a=a[D]("?");a=a[a[A]-1][D]("&");for(var c=0;c<a[A];c++){var d=a[c][D]("=");if(d[0])try{b[d[0][Ga]()]=d[A]>1?window.decodeURIComponent?ca(d[1][t]($c," ")):unescape(d[1]):""}catch(e){}}return b}function ad(a){a=a||m.URL;this.ga=Zc(a)}ad[B].getParameter=function(a){return a==g?g:this.ga[a]};ad[B].setParameter=function(a,b){this.ga[a]=b};
var bd=function(){if(!Yb)return"http://"+Oa("","pubads.g.doubleclick.net");return"https://"+Oa("","securepubads.g.doubleclick.net")};function cd(a){return a[t](/&/g,"&amp;")[t](/</g,"&lt;")[t](/>/g,"&gt;")[t](/\"/g,"&quot;")}function dd(){this.F=g;this.ha=i;this.ta=(new Date)[r]()}
var fd=function(a,b){if(a.F==g)if(!a.ha){a.F=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.F){var c=a.F[C],d=[];d[q]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');
d[q]("<p>Google Ad Capture Window</p>");for(var e in b)U(b[e])||d[q](ed(a,e,b[e]));d[q]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[q]("<script>displayTime('blocked', pageStartTime);<\/script>");d[q]("<p>Total Page Load Time (ms): <label id='total'></label>");d[q]("</body>\n</html>");a=d[J]("\n");(b=window.GA_googleEnv[y]("google_capture_norender")!=g)?c[w](cd(a)):c[w](a);c.close()}else a.ha=f}},ed=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";
var d="<p>Slot "+b+"</p>";c=c==g||c[x]==g?"No ad":c[x];var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function gd(a){this.f={};this.D=a}var hd=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.D)if((d=typeof d=="undefined"||d)||!a.f[b])a.f[b]=c}},id=function(a,b){for(var c in b.f)U(b.f[c])||a.f[c]||(a.f[c]=b.f[c])};
gd[B].getAttribute=function(a){return this.f[a]};gd[B].i=function(){var a=[];for(var b in this.f)if(!U(this.f[b])){var c=Zb[b]||$b[b]||ac[b]||g,d=this.f[b];c&&d&&a[q](c+"="+N(d))}return a[J]("&")};
var kd=function(a,b,c,d){a=jd(a,b,c,d);b=[];a[0]&&a[0][A]>0&&b[q](a[0][J]("&"));a[1]&&a[1][A]>0&&b[q]("sps="+a[1][J]("|"));return b[J]("&")},jd=function(a,b,c,d){var e=[],l=[];b=b.f;for(var h in d)if(!U(h)){var n=d[h];if(n){var u="";if(b[h]!=g)u=N(b[h]);var P=[],H=-1,Fa=-1;for(var Cb in a)if(!U(a[Cb])){++H;if(c[Cb]==g)P[q]("");else{var Ub=c[Cb].f;if(Ub[h]!=g){P[q](N(N(Ub[h])));Fa=H}else P[q]("")}}if(Fa>=0){H=N(u);u=[];u[q](H);for(H=0;H<=Fa;++H)u[q](P[H]);l[q](n+","+u[J](","))}else u&&e[q](n+"="+u)}}a=
[];a[q](e);a[q](l);return a};function ld(a,b){this.K=a;this.t=b;this.Y=0;this.qa=this.R=this.X=i;this.oa=this.pa=this.aa=this.la=g}var md=function(a){a.R=f;a.la=(new Date)[r]()},nd=function(a){a.aa=(new Date)[r]()},od=function(a){a.qa=f;a.pa=(new Date)[r]()},pd=function(a){a.oa=(new Date)[r]()};ea(ld[B],function(){return"[GA_GoogleAdSlot: pubid="+this.K+", name="+this.t+", loaded="+this.X+", tries="+this.Y+"]"});
function Wc(a){this.b={};this.d=[];this.s={};this.D=a;this.fa=new gd(this.D);this.B={};this.ka=i;this.p=g}
var Ec=function(a,b,c){b=new ld(b,c);return a.b[b.t]=b},qd=function(a,b){var c=[];for(var d in a.b)if(!U(a.b[d])){if(b){var e=Pc(a,d);if(e==g||!e._enabled_)continue}e=a.b[d];e.R||c[q](e)}return c},rd=function(a,b){return qd(a,b)[A]},sd=function(a){var b=[];for(var c in a.b){var d=a.b[c];U(d)||d.R&&d.aa==g&&b[q](c)}return b},td=function(a){var b=0;for(var c in a.b)if(!U(a.b[c])){var d=Pc(a,c);d!=g&&d._enabled_&&b++}return b},ud=function(a){for(var b in a.b)if(!U(a.b[b])){var c=a.b[b];md(c)}},vd=function(a,
b){a=a.b[b];md(a)},wd=function(a,b){a=a.b[b];nd(a)},xd=function(a,b){a=a.b[b];od(a)},yd=function(a,b){b=a.b[b];pd(b);Cc(T,"ga_render",a.d[A],"ga_srt")},zd=function(a){var b=0;for(var c in a.b)U(a.b[c])||b++;return b};ea(Wc[B],function(){var a="[AdData:",b=[];for(var c in this.b)U(this.b[c])||b[q](this.b[c][z]());for(var d in this.s)U(this.s[d])||b[q]("["+d+","+this.s[d]+"]");a+=b[J]();a+="]";return a});
var Ad=function(a,b){return a.b[b]},Bd=function(a,b,c){if(!(b==g||b[A]==0)){if(c==g||c[A]==0)c="";var d=a.s[b];a.s[b]=d==g?c:d+","+c}};function Cd(a,b){Bd(V(),a,b)}L("GA_googleAddAttr",Cd);var Dd=function(a,b,c){hd(a.fa,b,c)};function Ed(a,b){Dd(V(),a,b)}L("GA_googleAddAdSensePageAttr",Ed);var Fd=function(a){return a.fa},Gd=function(a,b,c,d){if(!(b==g||b[A]==0)){if(W()==g||W().h!="iframe"){var e=a.b[b];if(e==g)return}e=a.B[b];if(e==g)a.B[b]=new gd(a.D);hd(a.B[b],c,d)}};
function Hd(a,b,c){Gd(V(),a,b,c)}L("GA_googleAddAdSenseSlotAttr",Hd);var Id=function(a,b){return a.B[b]},Jd=function(){var a=bd();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},Jc=function(a){if(a.p!=g)W().k();else{var b=[];for(var c in a.b)U(a.b[c])||b[q](c);a=window.GS_googleGetIdsForAdSenseService();b=Jd(window)+"&client="+escape(a)+"&page_slots="+escape(b[J]());m[w]("<script src = '"+b+"'><\/script>")}},Kd=function(a,b){a.p=b;W().M=f;W().k()};function Ld(a){Kd(V(),a)}
L("GA_googleSetAdSlotAttributes",Ld);var Tc=function(a,b,c){if(a.p==g)a.p={};a.p[b]=c;W().M=f},Pc=function(a,b){return a.p!=g?a.p[b]:g};function Md(a,b,c){if(!c||c<0||c>1)c=0;this.ra=o[Ba]()<c;this.ma=a;this.Z=b+"/pagead/gen_204?id="+N(a);this.na=[]}
var X=function(a,b,c){if(b&&b[na](/^\w+$/)&&c)a.Z+="&"+b+"="+N(c)},Nd=function(a){var b=V();for(var c in b.b){var d=b.b[c];if(!U(d)&&d.K!=g){X(a,"pub_id",d.K);break}}X(a,"nslots",zd(b)[z]());X(a,"pub_url",m.URL);X(a,"pub_ref",m[ra])},Od=function(a){if(!a.ra||!a.ma||!a.Z)return i;var b=new Image;b.src=a.Z;a.na[q](b);return f};function Y(a){this.j=g;this.p={};this.q=this.c="";this.m=a;this.n=this.J=this.u=i;this.h="sync";this.sa=Zb;this.v=f;this.M=i}
var Hc=function(a){a.u=window.GA_googleEnv[y]("google_nofetch")!=g||window.google_noFetch;a.J=window.GA_googleEnv[y]("google_norender")!=g;a.n=window.GA_googleEnv[y]("google_capture")!=g||window.GA_googleEnv[y]("google_capture_norender")!=g;if(a.n)a.J=f;Pd(a,window);a.c=a.q;var b=Ia(a.ea,a);Qd(a,window,b)},Qd=function(a,b,c){if(b[sa]){b[sa]("onload",c);return f}if(b[qa]){b[qa]("load",c,i);return f}return i};Y[B].G=function(){this.n&&fd(window.GA_googleAdCapture,this.j)};
var Rd=function(a){if(a.h=="sync_sra"){var b=V(),c=zd(b);b=b.d[A];if(c!=b){a.I=new Md("sra_mismatch",bd(),Vb);X(a.I,"correlator",a.g);X(a.I,"fslots",b[z]());Nd(a.I);Od(a.I)}}},Sd=function(a){T.tick("ga_onload");T.report(a.h)},Td=function(a){var b=sd(V());if(b[A]>0){a.A=new Md("missing_cb",bd(),Tb);X(a.A,"pending",b[J]());X(a.A,"correlator",a.g);X(a.A,"impl",a.h);Nd(a.A);Od(a.A)}};Y[B].ea=function(){Sd(this);this.G();Rd(this);Td(this)};
var Pd=function(a){var b=window.GA_googleEnv[y]("google_ad_url");if(b==g||b[A]==0)a.q=bd()+"/gampad/ads?";else{if(b[ka](b[A]-1)!="?")b+="?";a.q=b}};Y[B].l=function(){};
var Qc=function(a,b){return a.j!=g?a.j[b]:g},Ud=function(){var a=j[E],b=a[v]("MSIE ");return b==-1?0:parseFloat(a[I](b+5,a[v](";",b)))},$c=/\+/g,Vd=function(a,b){b=b[Ga]();if(b[I](0,3)!="ca-")b="ca-"+b;return b},$=function(a,b,c){c!=g&&Z(a,b,N(c[z]()))},Z=function(a,b,c){if(c!=g&&c!="")a.c+=a.c[ka](a.c[A]-1)!="?"?"&"+b+"="+c:b+"="+c},Wd=function(a,b){for(var c=qd(V(),a.v),d=[],e=[],l=[],h=c[A],n=0;n<h;n++){var u=c[n];l[q](u.t);if(!(b!=g&&b!=u.t)){d[q](u.t);e[q](Vd(a,u.K))}}$(a,"client",e[0]);if(a.m)l[A]>
0&&$(a,"page_slots",l[J]());else{$(a,"slotname",d[J]());V().d[A]>0&&$(a,"page_slots",V().d[J]())}},Xd=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b[v]("google_preview=",a);c=b[v]("&",a);if(c==-1){c=b[A]-1;a-=1}return b[I](0,a)+b[I](c+1,b[A])}return b},Yd=function(a,b,c){if(xc(b,c))return c.URL;return c[ra]},$d=function(a,b,c){if(Zd(a,b,c)!=c.URL)return c[ma];return""},Zd=function(a,b,c){var d=Fd(V()).getAttribute("google_page_url");if(d)return d;return Yd(a,b,c)},ae=function(a,b,c,d){$(a,"url",
Xd(a,Zd(a,window,m),window.GA_googleEnv[y]("google_preview")));$(a,"ref",m[ra]);$(a,"lmt",(Date.parse(m.lastModified)/1E3)[z]());Z(a,"dt",b[va]());if(m[ya]){b=m[ya].scrollHeight;var e=m[ya].clientHeight;e&&b&&$(a,"cc",o[ga](e*100/b)[z]())}b=f;if(b=Db(b)){$(a,"biw",b[s]);$(a,"bih",b[Ea])}b=ec();$(a,"ifi",hc(b,13,gc(b,13)+1));b=Fb(window);b!=0&&$(a,"ifk",b[z]());b=window.GA_googleEnv[y]("deb");b!=g&&$(a,"deb",b);b=window.GA_googleEnv[y]("haonly");b!=g&&$(a,"haonly",b);b=Fd(V());j[E][v]("MSIE ")>0&&
hd(b,"google_encoding",m.charset,i);e="";if(d)e=kd(V().b,b,V().B,a.sa);else{c=Id(V(),c);if(c==g)c=b;else id(c,b);e=c.i()}if(e)a.c+="&"+e},be=function(a,b,c){var d=V().s,e=[];for(var l in d)U(d[l])||e[q](N(l)+"="+N(d[l]));$(a,"cust_params",e[J]("&"));if(b._GA_googleCookieHelper){$(a,"cookie",b._GA_googleCookieHelper.w);b._GA_googleCookieHelper.P&&$(a,"cookie_enabled","1")}(b=$d(a,b,c))&&$(a,"cdm",b)},ce=function(a){jc();var b=window;Z(a,"ga_vid",b.gaGlobal.vid);Z(a,"ga_sid",b.gaGlobal.sid);Z(a,"ga_hid",
b.gaGlobal.hid);Z(a,"ga_fc",b.gaGlobal.from_cookie);$(a,"ga_wpids",b.google_analytics_uacct)},de=function(a,b){for(var c in b){var d=b[c];U(d)||Z(a,c,d)}};
Y[B].i=function(a){this.l();var b=ee(this.g[z]()),c=fe();Z(this,"eid",[b,c][J](","));c=new Date;Wd(this,a);be(this,window,m);window.GA_googleEnv[y]("google_preview")!=g&&Z(this,"gct",window.GA_googleEnv[y]("google_preview"));ce(this);ae(this,c,a,this.m);a={};Bb(a);de(this,a);Z(this,"flash",zb());this.c=this.c[I](0,2E3);this.c=this.c[t](/%\w?$/,"");if(b){b=this.h=="iframe"||this.h=="fallback"?"html":"json_html";Qb().registerAdBlockByType(b,this.c,f)}return this.c};
var Oc=function(a){return a.v},ge=function(a,b){a=b.getAttribute("id");return a=a.substr(18,a[A]-18)},he=function(a,b,c,d){a='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:block;">'+d+"</ins>";return b='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:inline-table;">'+a+"</ins>"},je=function(a,b,c,d,e,l){var h="google_ads_iframe_"+b,n=[];b="google_ads_div_"+b;var u="border:0px;";if(ie(window))u+="left:0;position:absolute;top:0;";n[q]("<iframe id=",
h," name=",h,' width="',e,'" height="',l,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.n?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" ','style="',u,'"',' src="',cd(c),'"');d!=g&&n[q](' onload="',d,'"');n[q]("></iframe>");c=[];n=n[J]("");c[q]("<div id=",b,">");ie(window)?c[q](he(a,e,l,n)):c[q](n);c[q]("</div>");a=c[J]("");m[w](a)},ke=function(a,b,c){var d=Qc(a,c),e=d[za],l=d[la];d=d[x];var h=m[pa]("iframe");h.id="google_ads_iframe_"+c;h.name="google_ads_iframe_"+
c;da(h,e);fa(h,l);h.vspace=0;h.hspace=0;h.allowTransparency="true";h.scrolling="no";h.marginWidth=0;h.marginHeight=0;h.frameBorder=0;h[G].border=0;b=m.getElementById(b);if(ie(window)){h[G].position="absolute";h[G].top=0;h[G].left=0;var n=m[pa]("ins");da(n[G],e+"px");fa(n[G],l+"px");n[G].border=0;n[G].display="block";n[G].position="relative";var u=m[pa]("ins");da(u[G],e+"px");fa(u[G],l+"px");u[G].border=0;u[G].display="inline-table";u[G].position="relative";n[p](h);u[p](n);b[p](u)}else b[p](h);if(a.n){h[ua][C][w](cd(d));
h.scrolling="auto"}else h[ua][C][w](d);ie(window)?h[ua][C][w]("<script>document.close();<\/script>"):h[ua][C].close();yd(V(),c)};function le(a,b){ke(W(),a,b)}L("GA_googleCreateDomIframe",le);
var me=function(){var a=[],b=m[wa]("base");if(b)for(var c=0,d=b[A];c<d;++c){var e=b[c],l=e.getAttribute("target");if(l){a[q]({baseElement:e,originalTagValue:l});e.removeAttribute("target")}}return a},ne=function(a){if(a)for(var b=0,c=a[A];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},oe=function(a){var b="http://"+Pa()+"/pagead/inject_object_div.js";if(k(Ud(),10)>6)return i;if(a[v](b)<0)return i;return f},pe=function(a,b,c){if(a.n)c=cd(c);a=me();window.frames[b[ta]].contents=
c;b.src=oe(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';ne(a)},qe=function(a,b,c){var d=ge(a,b);try{var e=b[ua]?b[ua][C]:b.contentDocument;if(e==g)if(m.implementation&&m.implementation.createDocument)e=m.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return i;e.open("text/html","replace");a.n?e[w](cd(c)):e[w](c);e.close()}catch(l){return i}return f},re=function(a,
b){var c=ge(a,b),d=Ad(V(),c);if(!d.X){d.X=f;d=Qc(a,c);var e=b.parentNode;if(d==g||d[x]==g)e.removeChild(b);else if(d._expandable_&&!(d[Ca]&&d._is_3pas_))e.innerHTML=d[x];else d._is_3pas_?pe(a,b,d[x]):qe(a,b,d[x]);yd(V(),c)}},se=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";a=Qc(a,b);if(a!=g){c+=a[x];c+="\n</div>\n";m[w](c);yd(V(),b)}},te=function(a,b){a="google_ads_div_"+b;b="<div id="+a+">";b+="\n</div>\n";m[w](b);return a},ue=function(a){if(!a.v)return f;if(rd(V(),a.v)>0)return f;else if(td(V())==
0)return i},ve=function(a,b){Cc(T,"ga_srt",V().d[A],"_ga_start");if(a.j==g){a.j=b;for(var c in b)U(b[c])||wd(V(),c)}else for(c in b)if(!U(b[c])){a.j[c]=b[c];wd(V(),c)}a=i;for(c in b)if(!U(b[c])){var d=b[c];if(a){d._cookies_=[tc(window._GA_googleCookieHelper)];a=i}d!=g&&d._cookies_!=g&&window._GA_googleCookieHelper.L(d)}};function we(a){ve(W(),a)}L("GA_googleSetAdContentsBySlot",we);function xe(a){Y[Aa](this,a);this.v=i;this.g=(new Date)[va]();this.h=a?"sync_sra":"sync"}Ka(xe,Y);
xe[B].l=function(){this.c=this.q;$(this,"correlator",this.g[z]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlotForSync");this.m?Z(this,"impl","ss"):Z(this,"impl","s");ye(this,V().d);this.m||ze(this,V().d,this.j)};
var ye=function(a,b){for(var c=0,d=f,e=0;e<b[A];++e){var l=a.j&&a.j[b[e]];if(l)if(l[Ca]==ba){d=i;break}else c=2*c+(l[Ca]?1:0)}d&&Z(a,"prev_afc",c)},ze=function(a,b,c){if(b&&c){for(var d=[],e=[],l=b[A]-1,h=0;h<l;h++){var n=b[h];if((n=c[n])&&n._cids_&&n._a2ids_){d[q](n._cids_[0]);e[q](n._a2ids_[0])}else{d[q]("");e[q]("")}}if(d[A]>0){b=d[J](",");e=e[J](",");$(a,"a2ids",e);$(a,"cids",b)}}},Ae=function(a,b){var c=V().b;c=c[b];if(c!=g)if(!a.u){a.i(c.t);vd(V(),b);m[w]("<script src = '"+a.c+"'><\/script>")}},
Ce=function(a,b){ve(a,b);if(a.m)if(V().d[A]==1){b=V().d[0];Be(a,b);return}for(var c in b)U(b[c])||Be(a,c)};function De(a){Ce(W(),a)}L("GA_googleSetAdContentsBySlotForSync",De);xe[B].k=function(){ue(this)};var Ee=function(a){a.i(g);m[w]("<script src = '"+a.c+"'><\/script>");ud(V())};xe[B].o=function(a){V().d[q](a);Cc(T,"_ga_start",V().d[A]);if(this.m)V().d[A]==1?Ee(this):Be(this,a);else Ae(this,a)};
var Fe=function(a,b,c){if(b.google_js_backfill){a="script";c[w]("<"+a+' src="'+tb+'"></'+a+">")}},Be=function(a,b){Ge(a,window,m,b)},Ge=function(a,b,c,d){var e=Ad(V(),d);if(e!=g){e=Qc(a,d);xd(V(),d);if(e==g||e._empty_){Fe(a,b,c,d);yd(V(),d)}else if(a.J&&!a.n)yd(V(),d);else if(e._snippet_&&!e[Ca]&&!a.n)se(a,d);else if(b[Da][E][v]("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var l="about:blank";if(b=b.GA_googleEnv[y]("google_domain_reset_url")){var h=zc(b[na](yc)[3]||g);if(h===g||h[v](m[ma])>=0)l=
b}je(a,d,l,c,e[za],e[la])}else{a=te(a,d);c[w]("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},He=function(a,b){var c=ge(a,b);Ad(V(),c);re(a,b)};function Ie(a){He(W(),a)}L("GA_googleSyncAdSlotLoaded",Ie);function Je(a){Y[Aa](this,a);this.g=(new Date)[va]();this.h="async"}Ka(Je,Y);Je[B].l=function(){this.c=this.q;Ke(this);$(this,"correlator",this.g[z]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlot");Z(this,"impl","a")};
var Ke=function(a){a.delay=500;var b=window.GA_googleEnv[y]("google_async_delay");if(b!=g)a.delay=1E3*b};Je[B].k=function(){if(ue(this))this.u||window.setTimeout("GA_googleReallyFetchAds();",20)};var Le=function(a){if(rd(V(),a.v)!=0){var b=m[wa]("head")[0];if(a.m){var c=m[pa]("script");c.src=a.i(g);b[p](c);ud(V())}else{var d=V().b;for(var e in d)if(!U(d[e])){c=m[pa]("script");c.src=a.i(e);b[p](c);vd(V(),e)}}}};function Me(){Le(W())}L("GA_googleReallyFetchAds",Me);
Je[B].o=function(a){var b=Ad(V(),a);if(b!=g){V().d[q](a);b="GA_googleAsyncAdSlotLoaded(this);";var c=Pc(V(),a);je(this,a,"about:blank",b,c[za],c[la])}};var Oe=function(a,b){var c=ge(a,b);Ad(V(),c);!a.u&&!a.J&&Ne(a,b)};function Pe(a){Oe(W(),a)}L("GA_googleAsyncAdSlotLoaded",Pe);var Ne=function(a,b){var c=ge(a,b),d=Ad(V(),c);if(a.j==g||a.j[c]==g){if(!(d.Y>30)){window.setTimeout(function(){Ne(W(),b)},a.delay);d.Y++}}else re(a,b)};Je[B].G=function(){};
function Qe(a){Y[Aa](this,a);this.g=(new Date)[va]();this.h="fallback"}Ka(Qe,Y);Qe[B].l=function(){this.c=this.q;$(this,"correlator",this.g[z]());Z(this,"output","html");Z(this,"impl","fb")};Qe[B].k=function(){ue(this)};Qe[B].z=function(a){if(this.m){this.i(g);a=this.c+"&currentslot="+N(a)}else a=this.i(a);return a};Qe[B].o=function(a){var b=Pc(V(),a);if(b!=g){V().d[q](a);if(!this.u){var c=this.z(a);je(this,a,c,g,b[za],b[la])}}};
function Re(a){Y[Aa](this,a);this.g=(new Date)[va]();this.M=f;this.h="iframe"}Ka(Re,Y);Re[B].l=function(){this.c=this.q;$(this,"correlator",this.g[z]());Z(this,"output","html");Z(this,"impl","ifr")};Re[B].k=function(){ue(this)};Re[B].z=function(a){if(this.m){this.i(g);a=this.c+"&currentslot="+N(a)}else a=this.i(a);return a};Re[B].o=function(a){var b=Pc(V(),a);if(b!=g){V().d[q](a);if(!this.u){var c=this.z(a);je(this,a,c,g,b[za],b[la])}}};
var Se=function(){if(yb()){var a=Ud();return a<=5}else if(wb("firefox")){var b=j[E][v]("Firefox")+8;a=k(j[E][ka](b),10);b=j[E][ha](b);return a<1}else if(wb("safari")){b=j[E][v]("Safari")+7;b=j[E][ha](b);a=k(b,10);return a<412}else if(window[oa]!=g){b=j[E][v]("Opera")+6;b=j[E][ha](b);a=k(b,10);return a<9}else if(!yb()&&!wb("safari")&&wb("mozilla")){b=j[E][v]("Netscape")+9;b=j[E][ha](b);a=k(b,10);return a<7}else return f},Te=function(){if(yb()){var a=Ud();return a>5}else if(wb("firefox")){a=j[E][v]("Firefox")+
8;var b=k(j[E][ka](a),10);j[E][ha](a);return b>1}return i},Ue=function(){if(Se())return"fallback";else if(window.google_delayFetch&&Te())return"async";return"sync"},Gc=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=window.GA_googleEnv[y]("google_ad_impl");if(b==g)b=Ue()}switch(b){case "async":return new Je(i);case "sync":return new xe(i);case "sync_sra":return new xe(f);case "fallback":return new Qe(i);case "iframe":return new Re(i);default:return new Qe(i)}},Ve;
function V(){Ve||(Ve=new Wc(Zb));return Ve}function Vc(a){delete Ve;Ve=a}var We;function W(){We||(We=g);return We}function Fc(a){delete We;We=a}if(typeof window.GA_googleEnv=="undefined")window.GA_googleEnv=new ad;if(typeof window.GA_googleAdCapture=="undefined")window.GA_googleAdCapture=new dd;if(window._GA_googleCookieHelper==g)window._GA_googleCookieHelper=new oc(g);
function ee(a){var b=Qb(),c=b.getEid();if(c==""){if(c=Xe(window)){var d=b.getOsdMode();if(c=="36815006"||c=="36813008"){b.setValidOutputTypes(["html","json_html"]);d=c=="36815006"?1:0}b.setupOsd(d,c,a)}}else if(c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007")c="";return c}function fe(){var a=ec();if(gc(a,13)>0)return window.google_expandable_exp_id;a=Ab(["31865000","31865001"],Sb);return window.google_expandable_exp_id=a}
function Xe(){var a=ec();if(gc(a,13)>0)return"";a=Ab(["36815005","36815006"],Wb);if(a=="")a=Ab(["36813007","36813008"],Xb);return a}function ie(a){return a.google_expandable_exp_id=="31865001"}T.tick("js_parse","js_load");T.tick("jl");})()
